#
# Makefile for "codular-make"
#

#
# Target: build
#
build: build-css build-js
	@echo "Compress the assets!"

#
# Target build-js
#
build-js:
	@echo "Building js!"

#
# Target build-css
#
build-css:
	@echo "Building css!"

#
# Define all the targets above as PHONY
#
.PHONY: build-js build-css
